[project]
name = "geminimcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.21.2",
]

[project.scripts]
geminimcp = "geminimcp.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/geminimcp"]

[tool.uv]
package = true